name: 'Semantic'

on:
  push:
    branches: [main, next, next-major]

jobs:
  releasePackages:
    name: Release packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm i

      - name: Generate release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        id: semantic-release

      - name: Build @astral/ui
        if: env.CURRENT_VERSION != env.NEXT_VERSION
        run: npm run unknown

      - name: NEWW @astral/ui
        if: env.CURRENT_VERSION != env.NEXT_VERSION
        run: echo "${{ env.NEXT_VERSION }}"

      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        if: failure() || env.CURRENT_VERSION != env.NEXT_VERSION
        with:
          tag_name: ${{ env.NEXT_VERSION }} #(required) tag name to delete
          delete_release: true #(optional) default: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
