name: 'Release'

on:
  release:
    types: [released]

jobs:
  releasePackages:
    name: Release packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo Test
